language: python
python: "2.7"
before_install:
install:
- mkdir -p ~/sites/bodl-dmt-svc
- cd ~/sites/bodl-dmt-svc
- git clone https://github.com/bodleian/dmt.manifestcompiler.git ./
- virtualenv .
- . bin/activate
- pip install zc.buildout
- pip install distribute
- pip install lxml
- buildout init
- buildout -c development.cfg
script: 
- python src/dmt.manifestcompiler/dmt/manifestcompiler/importFiles.py -p src/dmt.manifestcompiler/dmt/manifestcompiler/test/images/ -t jp2 -i http://example.com/images/ -m http://example.com/meta/ -ht 500 -wt 500
- python src/dmt.manifestcompiler/dmt/manifestcompiler/importMETS.py -p src/dmt.manifestcompiler/dmt/manifestcompiler/test/xml/mets.xml -i http://example.com/images/ -m http://example.com/meta/ -ht 500 -wt 500
after_success: 

